import YAML from "yaml";

// We deliberately never ask the model to emit YAML text directly. LLMs are
// unreliable at exact indentation/quoting, and one bad YAML file defeats the
// entire point of this tool. Instead the model returns structured JSON
// (validated in server.js) and this file turns that into YAML the same way
// every time.

function buildZeropsYaml(services) {
  const entries = services
    .filter((s) => s.kind !== "managed") // managed services never get a build/run block
    .map((s) => {
      const entry = { setup: s.hostname };

      if (s.build) {
        entry.build = {
          base: s.build.base,
          buildCommands: s.build.buildCommands,
          deployFiles: s.build.deployFiles,
        };
      }

      if (s.run) {
        const run = {};
        if (s.run.base) run.base = s.run.base;
        if (s.run.ports?.length) run.ports = s.run.ports;
        if (s.run.start) run.start = s.run.start;
        if (s.run.envVariables && Object.keys(s.run.envVariables).length) {
          run.envVariables = s.run.envVariables;
        }
        entry.run = run;
      }

      return entry;
    });

  const doc = { zerops: entries };
  const header = `# zerops.yaml — build & deploy pipeline config\n# Generated by Auto-Architect. Place this at the root of the relevant\n# service's repository. See https://docs.zerops.io/zerops-yml/specification\n`;
  return header + YAML.stringify(doc, { indent: 2 });
}

function buildProjectImportYaml(services, projectName) {
  const entries = services.map((s) => {
    const entry = { hostname: s.hostname, type: s.type };
    if (s.kind === "managed" && s.mode) entry.mode = s.mode;
    if (s.enableSubdomainAccess) entry.enableSubdomainAccess = true;
    return entry;
  });

  const doc = {
    project: { name: projectName || "auto-architect-app" },
    services: entries,
  };
  const header = `# zerops-project-import.yaml — one-shot infra description\n# Paste this into "Import project" in the Zerops GUI, or run:\n#   zcli project project-import zerops-project-import.yaml\n# See https://docs.zerops.io/references/import for the full spec.\n`;
  return header + YAML.stringify(doc, { indent: 2 });
}

export function buildYamlOutputs(parsed) {
  const services = parsed.services || [];
  return {
    zeropsYaml: buildZeropsYaml(services),
    projectImportYaml: buildProjectImportYaml(services, parsed.projectName),
  };
}
